version: 0.2
   
phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem update --system
      - gem install bundler
      - bundle install
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://acloud.ninja
