version: 0.2
   
phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install jekyll jekyll-paginate-v2 jekyll-sitemap jekyll-gist jekyll-feed jekyll-seo-tag jekyll-archives minima
  build:
    commands:
      - echo "******** Install Gems ********"
      - bundle install
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://acloud.ninja
